language: node_js
node_js:
    - 8
install:
    - npm install
    - npm install -g cypress
    - npm install -g travis-ci-cloudfront-invalidation
    - npm install -g serve
    - pip install --user awscli

before_script:
    - CI=false npm run build

script:
    - serve -p 3000 -s build/ &
    - API_TARGET=develop cypress run --config video=false

branches:
  only:
  - master
  - staging
  - develop

jobs:
  include:
    - # if branch name develop use dev api url not prod
      if: branch = develop
      env: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
    - # if branch name staging **copied master line below can change when have APIURL
      if: branch = staging
      env: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STAGE
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STAGE
        - API_TARGET=staging
    - # if branch name master still build otherwise travis will say there are no jobs
      if: branch = master
      env: 
        - API_TARGET=prod
# regina-web-webbucket-1bd02ak8icken
deploy:
- provider: script
  script: ~/.local/bin/aws s3 sync build s3://mon-amie-web-webbucket-haxy607151if --region=us-east-1 --delete
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: ~/.local/bin/aws s3 sync build s3://mon-amie-web-stage-webbucket-2jpa2l3vc69a --region=us-east-1 --delete
  skip_cleanup: true
  on:
    branch: staging
- provider: script
  script: ~/.local/bin/aws s3 sync build s3://mon-amie-web-prod-webbucket-1w1zbb67azzrw --region=us-east-1 --delete
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID_DEV -s $AWS_SECRET_ACCESS_KEY_DEV -c 'EKK4BMPBI7M69' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -i '/*' -o 'develop'
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID_STAGE -s $AWS_SECRET_ACCESS_KEY_STAGE -c 'E2FM4QEO6YRBVE' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -i '/*' -o 'staging'
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c 'E3APW6BS2P1B19' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -i '/*' -o 'master'
