language: node_js
node_js:
    - 8
install:
    - npm install
    - npm install -g cypress
    - npm install -g travis-ci-cloudfront-invalidation
    - npm install -g serve
    - pip install --user awscli

before_script:
    - CI=false npm run build

script:
    - serve -p 3000 -s build/ &
    - API_TARGET=develop cypress run --config video=false

branches:
  only:
  - master
  - staging
  - develop

jobs:
  include:
    - # if branch name develop use dev api url not prod
      if: branch = develop
      env: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
    - # if branch name staging **copied master line below can change when have APIURL
      if: branch = staging
      env: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STAGE
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STAGE
        - API_TARGET=staging
    - # if branch name master still build otherwise travis will say there are no jobs
      if: branch = master
      env: 
        - API_TARGET=prod

deploy:
- provider: script
  script: ~/.local/bin/aws s3 sync build s3://prerender-uplift-web-webbucket-1xbphcj3iglwu --region=us-east-1 --delete
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: ~/.local/bin/aws s3 sync build s3://uplift-staging-webbucket-gm3uuitamfvi --region=us-east-1 --delete
  skip_cleanup: true
  on:
    branch: staging
- provider: script
  script: ~/.local/bin/aws s3 sync build s3://uplift-web-prod-webbucket-18hdos6r2m7se --region=us-east-1 --delete
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID_DEV -s $AWS_SECRET_ACCESS_KEY_DEV -c 'E3SR6FJHQNNWTL' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -i '/*' -o 'develop'
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID_STAGE -s $AWS_SECRET_ACCESS_KEY_STAGE -c 'E3G7GMSMY3LY7W' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -i '/*' -o 'staging'
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c 'E1YKY2FO2MSJEP' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -i '/*' -o 'master'
